import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div classNameName={styles.container}>
      <Head>
        <title>Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="w3-content w3-margin-top" style={{ maxWidth: '1400px' }}>
        <div className="w3-row-padding">
          <div className="w3-third">
            <div className="w3-white w3-text-grey w3-card-4">
              <div className="w3-display-container">
                <image src={'/ploi.jpg'} width={100} height={100} alt="Avatar"/>
                <div className="w3-display-bottomleft w3-container w3-text-white">
                  <h2><b>PLOY</b></h2>
                </div>
              </div>
              <div className="w3-container">
                <h2 className="w3-text-light-blue"><b>Yasumin Simtama</b></h2>
                <p><i className="fa fa-briefcase fa-fw w3-margin-right w3-large w3-text-light-blue"></i>Student, RMUTI Isan</p>
                <p><i className="fa fa-home fa-fw w3-margin-right w3-large w3-text-light-blue"></i>Nakhon Ratchasima, TH</p>
                <p><i className="fa fa-envelope fa-fw w3-margin-right w3-large w3-text-light-blue"></i>yausimt@gmail.com</p>
                <p><i className="fa fa-phone fa-fw w3-margin-right w3-large w3-text-light-blue"></i>0954982096</p>
                <hr />

                <p className="w3-large"><b><i className="fa fa-asterisk fa-fw w3-margin-right w3-text-light-blue"></i>Skills</b></p>
                    <p>Adobe Photoshop</p>
                    <div className="w3-light-grey w3-round-xlarge w3-small">
                      <div className="w3-container w3-center w3-round-xlarge w3-light-blue" style={{width:'50%'}}>50%</div>
                    </div>
                    <p>Adobe Premiere Pro</p>
                    <div className="w3-light-grey w3-round-xlarge w3-small">
                      <div className="w3-container w3-center w3-round-xlarge w3-light-blue" style={{width:'50%'}}>
                        <div className="w3-center w3-text-white">50%</div>
                      </div>
                    </div>
                    <br/>

                    <p className="w3-large w3-text-theme"><b><i className="fa fa-globe fa-fw w3-margin-right w3-text-light-blue"></i>Languages</b></p>
                    <p>English</p>
                    <div className="w3-light-grey w3-round-xlarge">
                      <div className="w3-round-xlarge w3-light-blue" style={{height:'24px', width:'50%'}}></div>
                    </div>
                    <br/>
                    <br/>
                    <br/>
              </div><br/>


              <div className="w3-twothird" >
                <div className="w3-container w3-card w3-white w3-margin-bottom">
                  <h2 className="w3-text-grey w3-padding-24"><i className="fa fa-th-large fa-fw w3-margin-right w3-xxlarge w3-text-light-blue"></i><b>PORFOLIO</b></h2>
                  <div className="w3-container">
                    <h5 className="w3-opacity"><b>ABOUT ME</b></h5>
                    <h6 className="w3-text-light-blue"><i className="fa fa-calendar fa-fw w3-margin-right"></i>Oct 2000 - <span className="w3-tag w3-light-blue w3-round">Current</span></h6>
                    <p><b>Name</b> : Yasumin Simtama <b>Nickname</b> : Ploy
                      <br /><b>Date of Birht</b> : 5<sup>th</sup> October, 2000
                      <br /><b>Hobby</b> : Watching Anime, Movies & play a game </p>
                    <p><b>Address</b> : 21 Moo 11 Huaithaleang District, Nakhon Ratchasima 30000</p>
                    <hr />
                  </div>
                <div className="w3-container">
                  <h5 className="w3-opacity"><b>Education</b></h5>
                  <h6 className="w3-text-light-blue"><i className="fa fa-calendar fa-fw w3-margin-right"></i>2021 - <span className="w3-tag w3-light-blue w3-round">Current</span> </h6>
                  <h5><b>Rajamangala University of Technology Isan : RMUTI Isan</b></h5>
                  <p>
                    <dd>Bachelor of Business Administration Program in Business Computer (Continuing Program)
                      <br />: Bachelor Degree</dd>
                  </p>
                  <h6 className="w3-text-light-blue"><i className="fa fa-calendar fa-fw w3-margin-right"></i>2019 - 2020</h6>
                  <h5><b>Nakhonkorat Technical College : NTC </b></h5>
                  <p>
                    <dd>Business Computer : Diploma Degree
                    </dd>
                  </p>
                </div>
                
                <hr />

                <div className="w3-container">
                  <h5 className="w3-opacity"><b> Project</b></h5>
                  <h6 className="w3-text-light-blue">2022 <a href="http://isrmuti.com/sen/">Sen Service</a></h6><br />
                </div> <hr />
                <div className="w3-container">
                  <h5 className="w3-opacity"><b>Proverb</b></h5>
                  <h6 className="w3-text-light-blue"> <em>The only person you should try to be better than is the person you were yesterday.</em>
                    <br /> คนเดียวที่คุณควรพยายามจะดีกว่า คือตัวคุณในเมื่อวานนี้
                  </h6><br />
                </div>
              </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    <footer className="w3-container w3-light-blue w3-center w3-margin-top">
      <p className="w3-small">This is portfolio by Yasumin.</p>
    </footer>
    </div >
  )
}
